apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tory-bovid-go 
  janus-idp.io/tekton: tory-bovid-go
  backstage.io/kubernetes-id: tory-bovid-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tory-bovid-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  