apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tory-bovid-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tory-bovid-go 
  name: tory-bovid-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tory-bovid-go 
